### ISSUE TITLE
Kompatibilitätsprobleme Germanized Pro

### ISSUE THREAD

**Issue by vendidero** [PAYONE-GmbH/woocommerce-3#1]
Hi,

wir entwickeln das Plugin "WooCommerce Germanized" und auch die entsprechende Pro-Version. Leider gibt es mit eurem Plugin Probleme in unserer mehrstufigen Kasse, da offenbar per JS auf den Submit-Button zugegriffen wird. Wir würden uns das gerne näher anschauen und ein Kompatibilitätsscript dazu entwickeln. Dazu hätte ich folgende Fragen:

1. Gibt es bei euch einen Developer-Zugang über den wir Test-API-Daten beziehen können?
2. Gibt es die Möglichkeit das "hosted" JS-File "https://secure.pay1.de/client-api/js/v1/payone_hosted_min.js?ver=4.9.7" lokal und unminified zu beziehen?

Beste Grüße,
Dennis

**Comment by hreinberger** [comment]
Hi Dennis,

wir können euch gerne einen Zugang erstellen, schick uns dazu bitte kurz eine Mail mit deinen Kontaktdaten an integrations@bspayone.com. Eine lesbarere Version des Javascripts kannst du dir hier anschauen: https://secure.pay1.de/client-api/js/v1/payone_hosted.js 

Das Script gehört zur Tokenisierung von Kreditkartendaten während des Checkouts, daher binden wir uns hier an den Submit-button.

viele Grüße
Hannes

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.

**Comment by fjbender** [comment]
Wir hatten heute wieder einen Kunden im Support mit diesem Problem. Können wir hier irgendwie weiterhelfen @vendidero ?
