### ISSUE TITLE
WooCommerce Subscription

### ISSUE THREAD

**Issue by andreherful** [PAYONE-GmbH/woocommerce-3#110]
Hallo,

Wenn ich von Payone 2.1.0 auf 2.3.0 aktualisiere ist die Integration zu WooCommerce Subscription nicht mehr da bzw. funktioniert nicht mehr. Der Punkt heißt: Enable automatic failover for WooCommerce Subscriptions

Gibt es hierfür einen Grund?
Dankeschön!

**Comment by janteuber** [comment]
Hallo @andreherful ,

vielen Dank für deine Nachricht.

Diesen Punkt hatten wir eingebaut um uns mit einem Plugin für Abomodelle kompatibel zu machen. Da es hier aber zu Fehlern kam, haben wir entschieden auf die Kompatibilität zu verzichten und haben in der neuen Pluginversion die dazugehörigen Änderungen aus dem Code entfernt.

**Comment by andreherful** [comment]
Vielen Dank für die Antwort.  
Gibt es eine Alternative Lösung für das Problem?

**Comment by janteuber** [comment]
Nein, wir werden bis auf Weiteres keine Abomodelle unterstützen mit unserem Plugin.

**Comment by andreherful** [comment]
Das heißt auch nicht mehr über: https://docs.woocommerce.com/document/subscriptions/develop/payment-gateway-integration/ ?

**Comment by janteuber** [comment]
Dies haben wir ausgebaut.
