### ISSUE TITLE
Unfavorable name of the variable "Config" because of global scope

### ISSUE THREAD

**Issue by Bisdanner** [PAYONE-GmbH/woocommerce-3#111]
There are some issuse displaying creditcard input fields, because of the global scope of the variable "config". 

If there are other (global) "configs" the javascript function won't work properly. This can be recognized by the fact that the input fields for the credit card are not displayed.

https://github.com/PAYONE-GmbH/woocommerce-3/blob/0bf69b6433225f16b7644c2f5d42bda78c40b6de/views/gateway/creditcard/payment-form.php#L67

and

https://github.com/PAYONE-GmbH/woocommerce-3/blob/0bf69b6433225f16b7644c2f5d42bda78c40b6de/views/gateway/creditcard/payment-form.php#L69

A simple renaming of the variable config in line 67 to credit_card_config or payone_cc_config could be a easy solution.

**Comment by janteuber** [comment]
Hello @Bisdanner ,

Thank you for your message.

We will take a look at the case and will give you feedback.

**Comment by janteuber** [comment]
Hello @Bisdanner ,

I have feedback from our developer.

We will implement your suggestions and make further renaming. 

We will release these changes with the next plugin version (early 2023).

Thanks again for your comment.
