### ISSUE TITLE
Multiple Payone Accounts

### ISSUE THREAD

**Issue by rahxam** [PAYONE-GmbH/woocommerce-3#121]
Hello,
We have multiple vendors and would like to have one payone account per vendor. Would it be able to provide a hook to change key, account Id, ... for a payment so that we could determine the correct account settings based on the product in the cart?

Thanks,
Maximilian

**Comment by rahxam** [comment]
Hello @janteuber ,
Thanks for the quick reply. I know what needs to be done and I would be willing to build those logic by ourselves. But, it would be great if you could provide a hook which I could use to manipulate the settings during checkout. Otherwise, I would need to fork the repo and merge your changes regularly, which would make payone a very unpractical solution, as the stripe and PayPal plugins provide exactly those options.
Thanks and have a nice weekend,
Maximilian

**Comment by janteuber** [comment]
Hello @rahxam ,
We are aware that other competitors are further along in this area. Unfortunately, we cannot help here at the moment.
