### ISSUE TITLE
Code verursacht fatalen Error

### ISSUE THREAD

**Issue by heiko-bellafloor** [PAYONE-GmbH/woocommerce-3#130]
Ich habe versucht, die angegebenen Code-Zeilen per Snippet-Plugin in Wordpress / Woocommerce einzufügen und bekomme Fatal-Errors.
Ich bitte um kurzfristigen Lösungsweg, wie ich den Übergabefehler (Amountfehler) schnellstens beheben kann.
Diese Zeilen wurden versucht, einzufügen:
 */
	public function set_once( $key, $value ) {
		if ( ! isset( $this->parameter_bag[ $key ] ) ) {
			$this->parameter_bag[ $key ] = $value;
			$this->set( $key, $value );
		}

		return $this;

**Comment by dolbertz** [comment]
Hallo Herr Bellafloor,

ich bin mir nicht ganz sicher, welche Änderungen sie genau gemacht haben. Die Zeilen, die sie hier erwähnen, sind nur ein Ausschnitt aus dem endgültigen Code. Ich vermute, dass sie sich die Zeilen von hier kopiert haben: 
 - Commit https://github.com/PAYONE-GmbH/woocommerce-3/commit/7fef8ee278dbd291e13069a21c9b6a42abd009e6


Das ist ein sogenannter "Diff". Also der Unterschied zwischen der alten und der neuen Version der Datei. Letztendlich besagt der Diff, dass in der Datei woocommerce-3/src/Payone/Payone/Api/DataTransfer.php aus unserem Plugin die rot markierte Zeile 94 durch die grün markierte Zeile 94 ersetzt werden muss.

**Damit würden sie dem offiziellen Release der nächsten Version des Plugins vorgreifen. Unsere abschließenden Tests aller Änderungen für den nächsten Release stehen noch aus. Und wenn sie die angesprochene Änderung in Zeile 94 dieser Datei nicht korrekt ausführen, kann dies zu weiteren Beeinträchtigungen ihrer Installation führen.**

Ich kann aber bestätigen, dass der Austausch dieser Zeile in der aktuell vertriebenen Version des Plugins das Problem mit dem Übergabefehler beheben sollte.
