### ISSUE TITLE
Register plugin in official plugin registry of Wordpress.org

### ISSUE THREAD

**Issue by luflow** [PAYONE-GmbH/woocommerce-3#14]
Hi everyone!

I just wanted to suggest that the plugin should be registered on wordpress.org.

That would also lead to free access to the translation management in https://translate.wordpress.org/ which should be used for translations instead of shipping them in the repository.

AND it would create higher visibility for new woocommerce shop owners that want / consider to use BSPAYONE as PSP.

**Comment by fjbender** [comment]
Thanks for the suggestion! Currently, we haven't considered this option since Wordpress' Plugin Repo is on a SVN basis, which will create a headache of it's own. Do you have any best-practice guides at hand on how to maintain Git and the SVN-Plugin-Repo at the same time?

**Comment by luflow** [comment]
Maybe something like https://github.com/rayrutjes/wp-plugin-git-svn-sync ?

But I also asked in the woocommerce and wordpress slack about this problem - maybe there is even a better solution for that.

**Comment by luflow** [comment]
@fjbender just got an answer in the woocommerce Slack. The best thing to use is: https://github.com/mikejolley/github-to-wordpress-deploy-script

**Comment by fjbender** [comment]
Thanks for asking in the apropriate channels, @luflow! We'd probably go with Christian's approach. However, due to vacations it's going to take a couple of weeks.

**Comment by fjbender** [comment]
My plan was to make use of Travis' "Deploy on tagged commit only" feature (we're doing this for our Shopware repository, for instance). 

Mike's shell script looks great for an initial release, too :)

**Comment by hreinberger** [comment]
as @fjbender wrote, we're in the wordpress store already and already tested a Travis config. We'll implement this in the coming days (hopefully), so that every tagged release gets pushed to wordpress.org automatically. Closing this for now.
