### ISSUE TITLE
Probleme auf der Kassen-Seite

### ISSUE THREAD

**Issue by anjablubber123** [PAYONE-GmbH/woocommerce-3#17]
Hallo liebes Entwicklerteam, 

Ich habe das Problem dass bei der Auswahl der Kredikarte als Zahlungsmittel die Input Felder "Cardpan", "CVC" und "Expire Date", die als Iframe geladen werden sollten, leider leer sind. 
Die Iframes sind an sich da aber ohne Inhalt.
Die Seite läuft mit SSL - daran sollte es also nicht scheitern. 
Benutzt wird WooCommerce (in Version 3.5.1) mit WooCommerce Germanized (in Version 2.2.4) 

Hattest ihr das Problem schon mal bzw. könnt ihr mir einen Tipp geben, wie das zu beheben ist? 
Gibt es eine Doku zu eurem Plugin?

Vielen Dank für die Info!
LG

**Comment by hreinberger** [comment]
Hi @anjablubber123 
die Doku zum Plugin findest du hier in unserem docs-Repository. https://github.com/PAYONE-GmbH/docs/blob/master/BS%20PAYONE%20Payment%20Integration%20f%C3%BCr%20WooCommerce-v17-20181018_1401.pdf 

Wenn die iFrames nicht richtig geladen werden, kann das durch nicht geladenes Javascript im Checkout verursacht werden. Das ist aber meist eine shopindividuelle Sache. Bitte melde dich einmal bei unserem tech support unter tech.support[ät]bspayone.com unter Angabe deiner merchant ID und der Shop URL.

Die Kollegen schauen sich dann das Frontend und die Konfiguration des Accounts einmal an. Eventuell ist da noch etwas nicht richtig eingestellt.

**Comment by anjablubber123** [comment]
Super vielen Lieben Dank! Mache ich! 
Danke für die Doku!
