### ISSUE TITLE
SEPA Lastschrift // Subscription

### ISSUE THREAD

**Issue by UnknownX74** [PAYONE-GmbH/woocommerce-3#18]
Hallo zusammen, 

beim WooCommerce Shop sind mit Plugins ja auch wiederkehrende Zahlungen möglich, die wir nutzen wollen. 

Das ist leider mit dem Plugin so nicht vorgesehen – es gibt aber wohl eine (relativ einfache) Möglichkeit, das Plugin entsprechend zu erweitern. Dies von unserer Seite zu tun wäre der wahrscheinlich schlechteste Weg, da die Änderungen beim nächsten Update ja überschrieben würden. Außerdem dürften wir nicht die einzigen sein, die daran ein Interesse haben dürften ;-) 
 
Insofern würde ich mich freuen, wenn Sie eine Blick in die Doku von dem Subscription Modul werfen könnten, die Sie hier finden: https://docs.woocommerce.com/document/subscriptions/develop/payment-gateway-integration/
und mir dann eine Rückmeldung geben, ob und mit welchem zeitlichen Vorlauf eine entsprechende Anpassung möglich wäre.

Vielen Dank und viele Grüße

**Comment by fjbender** [comment]
Hi @UnknownX74 ,

ihr könnt das natürlich auch sehr gerne selbst bauen und hier einfach einen Pull Request stellen - wir testen das Ganze dann noch einmal genau durch und dann wird es in zukünftigen Versionen auch enthalten sein.

Viele Grüße
Florian

**Comment by UnknownX74** [comment]
Hallo Florian,

ich fürchte ganz so trivial ist das Ganze nicht, denn wir haben ja hier insb. bei SEPA die Mandats-Thematik und so wie ich es heute sehe, muss der Kunde dem SEPA-Mandat zustimmen - unabhängig, was in den Einstellungen im Menüpunkt "Use PAYONE Mandate Management" eingestellt ist. 

Selbst, wenn das beim ersten Mal sehr sinnvoll (und zweifelsfrei notwendig) sein mag, das Mandat erstellen zu lassen, muss (sollte) es danach in der Datenbank abgespeichert werden, damit das System bei den folgenden Lastschriften eben nicht an der Stelle "warte auf Userfreigabe" hängen bleibt. 

Das einzubauen ... dazu fehlt uns schlichtweg die Kenntnis vom Zusammenspiel der einzelnen Module... aber notwendig wäre für unser Geschäftsmodell sicherlich sehr ... :-) 

Wenn ich auf dem Holzweg bin ... bitte kurz abholen ;-)

Danke und viele Grüße
Stefan

**Comment by fjbender** [comment]
Moin Stefan,

grundsätzlich persistieren wir das SEPA Mandat bei uns auf der Plattform. Das gilt dann auch für alle folgenden Lastschriften. Bei Abschluss des Abos würde also das Mandat angezeigt und es wäre für alle folgenden Belastungen nicht mehr nötig.

@hreinberger ist der zuständige Produktmanager für WooCommerce und wird sich mit dem Thema in der nächsten Woche noch einmal genauer auseinandersetzen.
