### ISSUE TITLE
Zahlung in REST API ausführen

### ISSUE THREAD

**Issue by ltwmaster** [PAYONE-GmbH/woocommerce-3#19]
Moin Freunde,

wahrscheinlich drücke ich mich komplizierter aus als es eigentlich ist... 

Wir wollen woocommerce um den REST API-Endpoint erweitern, der auch Zahlungen verarbeiten kann. (Bzw. wir wollen die Order auslösen und im gleichen Zuge auch die Zahlung verarbeiten)
Am liebsten über dieses Plugin https://wordpress.org/plugins/wc-rest-payment/#description, dass wir dann selbst umschreiben. 

Gibt es irgendwo eine Dokumentation wie die entsprechenden PAYONE Funktionen heißen und wie wir diese selbst callen können? Am besten wäre es wenn wir die Funktion mit den entsprechenden Infos abschicken und dann eine Redirect URL erhalten an den wir den User weiterleiten. 

Am besten wäre wirklich eine Dokumentation der Funktionen dieses Plugins.

Beste Grüße
Lasse

**Comment by hreinberger** [comment]
Hi @ltwmaster 
die Doku unseres Plugins behandelt tatsächlich nur Back- und Frontend-Themen und geht nicht auf den Code ein. Das Plugin über die REST API anzusprechen, ist allerdings auch nicht wirklich vorgesehen. Unsere Plattform verhält sich da etwas anders als Stripe oder PayPal. In vielen Fällen fällt z.B. nicht nur ein Redirectlink heraus, sondern die Zahlung wird über mehrere Requests (z.B. bei Kreditkarte und SEPA Lastschrift) abgewickelt. 

Ich kenne euren genauen Usecase dazu nicht, aber evtl. wäre es für euch sogar praktikabler, unsere BS PAYONE API direkt anzubinden?

viele Grüße!

**Comment by ltwmaster** [comment]
Moin @hreinberger,

danke für die schnelle Antwort. 

Im Prinzip bauen wir den bestehenden REST API Controller so um, dass wir Zahlungen damit abwickeln können. Wir sind grundsätzlich offen dafür, dass mehrfach ein Austausch (z.B. preauthorize & im nächsten Schritt capture) passiert. Warum wir das machen? Weil uns der reguläre Checkout von Woocommerce nicht ausreicht und wir unser eigenes Front-End "aufsetzen". 

Ich weiß nur, dass wir uns auf die anderen Payment Gateways von Woocomerce recht gut aufsetzen können und die Funktionen auch in eigenen PHP Dateien callen können, um dann z.B. nachdem wir die Order auf erstellt haben, direkt die Zahlung abzuwickeln.

Wir wären aber natürlich auch offen dafür, dass direkt über die PAYONE API zu realisieren. Hättest du dafür eine Doku für mich?

Danke und Viele Grüße
ltwmaster
