### ISSUE TITLE
Article list faulty or incomplete [1610]

### ISSUE THREAD

**Issue by FrankWalle** [PAYONE-GmbH/woocommerce-3#20]
Hallo.
Im Magento - Thread gibt es einen gleichlautenden Fehler.
Wir benutzen das WP Plugin Version 1.4.0, Woocommerce 3.5.2 und die Germanized Version 2.2.4
Offensichtlich passiert es nicht bei jeder Kreditkarten-Zahlung.

Gibt es da eine Lösung?

Schönen Dank schon jetzt.

**Comment by FrankWalle** [comment]
Kleines Update... die Zahlung schlägt fehl sobald man einen Gutscheincode verwendet. Also tatsächlich ähnlich dem Fehler beim Magento-Plugin.

**Comment by hreinberger** [comment]
Hi @FrankWalle,
Der Fehler 1610 wird meist von unserer API geworfen, wenn die Summe der Einzelpreise nicht mit dem Gesamtpreis übereinstimmt. Bei Magento 1 kommt das meist durch Rundungsdifferenzen zustande. Bei Woocommerce ist mir das aber noch nicht aufgefallen. 

Bitte wende dich einmal mit deiner Merchant ID und der betreffenden Bestellung an unseren Tech Support unter tech.support[at]bspayone.com. Die Kollegen können dann genauer analysieren, was hier schief läuft.

**Comment by hreinberger** [comment]
PS: Ein Workaround kann sein, einmal die Übergabe des Warenkorbs zu deaktivieren. Die Einstellung findest du global hier: 
![grafik](https://user-images.githubusercontent.com/40197225/50884840-532a4700-13ec-11e9-9f0f-7f674f887c41.png)
