### ISSUE TITLE
Probleme mit Bedrock Installation

### ISSUE THREAD

**Issue by flymke** [PAYONE-GmbH/woocommerce-3#25]
Hallo zusammen,

wir haben folgendes Problem: Wir benutzen das Plugin auf einem WooCommerce Shop, der mit Bedrock Boilerplate aufgesetzt wurde (siehe https://roots.io/bedrock/). Problem ist, dass Bestellung über SEPA Anfragen per Ajax an eine falsche URL schicken:
`
https://www.shopseite.de/wp/payone-callback/?type=ajax-manage-mandate 404
`

Es müsste sein
`
https://www.shopseite.de/payone-callback/?type=ajax-manage-mandate
`
Also Home_URL + '/payone-callback/' (ohne /wp)

Hier scheint irgendwie die root URL der WordPress Installation abgefragt zu werden.

**Comment by flymke** [comment]
Gibt es hier schon was neues?

**Comment by hreinberger** [comment]
Hi @flymke 
leider noch nicht so richtig :( Wir sind dran und ich hoffe, dass wir diese Woche Neuigkeiten haben.
viele Grüße

**Comment by flymke** [comment]
Super danke für die Rückmeldung :) Ich glaube das Problem liegt darin, dass evtl. die site_url() aufgerufen wird anstatt die home_url(). Beste Grüße

**Comment by T-Kuchel** [comment]
Hallo @flymke ,

das Problem scheint in der Datei:
[~/src/Payone/Plugin.php](https://github.com/PAYONE-GmbH/woocommerce-3/blob/master/src/Payone/Plugin.php) #117 zu liegen:

`$url = get_site_url( null, self::CALLBACK_SLUG . '/' );`

und sollte wohl eher sein:

`$url = get_home_url( null, self::CALLBACK_SLUG . '/' );`

Kannst Du das bestätigen?

beste Grüße

**Comment by flymke** [comment]
Perfekt. Das wars! So funktioniert es. Danke!
