### ISSUE TITLE
Kompatibilität mit Woo 3.8 und WP 5.3?

### ISSUE THREAD

**Issue by oliverf72** [PAYONE-GmbH/woocommerce-3#36]
Guten Morgen,
in wie weit ist die aktuelle Version kompatibel mit Version 1.5.1?

**Comment by T-Kuchel** [comment]
Hallo und guten Morgen @oliverf72 ,

diese Version ist leider nicht zu 100% kompatibel, aber wir planen eine neue/s Version/Release spätestens in der kommenden Woche zu veröffentlichen.
Diese Version (der aktuelle master-branch) befindet sich gerade in unserer QA.

Beste Grüße aus Kiel
Timo

**Comment by oliverf72** [comment]
Hallo Timo,
ok, danke für das schnelle Feedback. Dann warten wir noch mit dem Update..
Gruß Oliver

**Comment by oliverf72** [comment]
Hallo Timo,
wie ist der aktuelle Stand?

**Comment by fjbender** [comment]
Wir haben leider noch ein paar Stolperfallen im Release-Test gefunden, deshalb ist aktuell noch nicht klar, ob das Release noch in dieser Woche kommt.

**Comment by oliverf72** [comment]
Guten Morgen,

wo sind denn Problem zu erwarten?

Bitte um Feedback. Vielen Dank… 

mit freundlichen Grüßen

Oliver Fröhner

 

FENOMICS© GmbH - Wilhelm-Trübner- Str. 3 - 69502 Hemsbach
Amtsgericht Mannheim - Registergericht: HRB 712643 - USt-IdNr.: DE278620454

Geschäftsführer: Wolfgang Embach, Dipl.-Betriebswirt (DH) Oliver Fröhner

Telefon Herr Fröhner: +49 6201 687658 Mobil: +49 151 57155799 

Telefon Herr Embach: +49 6201 6797905 Mobil: +49 160 94871577

https://www.fenomics.de Kundensupport: Ticketsystem

RECMAN der RECruiting MANager https://www.recman.de

 

 

Von: Florian Bender <notifications@github.com>
Antworten an: PAYONE-GmbH/woocommerce-3 <reply@reply.github.com>
Datum: Mittwoch, 27. November 2019 um 08:18
An: PAYONE-GmbH/woocommerce-3 <woocommerce-3@noreply.github.com>
Cc: oliverf72 <o.froehner@fenomics.de>, Mention <mention@noreply.github.com>
Betreff: Re: [PAYONE-GmbH/woocommerce-3] Kompatibilität mit Woo 3.8 und WP 5.3? (#36)

 

Wir haben leider noch ein paar Stolperfallen im Release-Test gefunden, deshalb ist aktuell noch nicht klar, ob das Release noch in dieser Woche kommt.

**Comment by fjbender** [comment]
Wir haben aktuell Schwierigkeiten, den appointed-Zahlstatus immer korrekt zu verarbeiten. Es kann zu Situationen kommen, wo Woocommerce den Status nach z.B. einem PayPal Redirect nicht empfängt und die Bestellung dann als "cancelled" angezeigt wird, obwohl Geld geflossen ist.

**Comment by hreinberger** [comment]
Hallo zusammen,

wir haben gerade die Version 1.6.1 sowohl hier als auch im Store veröffentlicht. Sorry für die Verzögerung.

**Comment by oliverf72** [comment]
Sehr gut, gerade rechtzeitig… sind heute online gegangen.. hoffen wir das alles funktioniert 😉

mit freundlichen Grüßen

Oliver Fröhner

 

FENOMICS© GmbH - Wilhelm-Trübner- Str. 3 - 69502 Hemsbach
Amtsgericht Mannheim - Registergericht: HRB 712643 - USt-IdNr.: DE278620454

Geschäftsführer: Wolfgang Embach, Dipl.-Betriebswirt (DH) Oliver Fröhner

Telefon Herr Fröhner: +49 6201 687658 Mobil: +49 151 57155799 

Telefon Herr Embach: +49 6201 6797905 Mobil: +49 160 94871577

https://www.fenomics.de Kundensupport: Ticketsystem

 

 

Von: Hannes Reinberger <notifications@github.com>
Antworten an: PAYONE-GmbH/woocommerce-3 <reply@reply.github.com>
Datum: Montag, 6. Januar 2020 um 13:25
An: PAYONE-GmbH/woocommerce-3 <woocommerce-3@noreply.github.com>
Cc: oliverf72 <o.froehner@fenomics.de>, Mention <mention@noreply.github.com>
Betreff: Re: [PAYONE-GmbH/woocommerce-3] Kompatibilität mit Woo 3.8 und WP 5.3? (#36)

 

Hallo zusammen,

wir haben gerade die Version 1.6.1 sowohl hier als auch im Store veröffentlicht. Sorry für die Verzögerung.

**Comment by oliverf72** [comment]
Hallo Herr Reinberger,
wie ist denn der Prozess um eine Paypal bestellung wieder zurück zu erstatten. Die Rückerstattungsfunktion in Woo hat im Payone Backend zu keiner Aktion geführt....

**Comment by oliverf72** [comment]
Zur Info für Mitleser: zumindest Paypalzahlung via Payone in Woo 3.8.1 funktioniert einwandfrei. Die anderen Zahlungsmethoden haben wir noch nicht getestet..

**Comment by hreinberger** [comment]
Moin @oliverf72 zum Thema Gutschriften hilft vielleicht unsere Doku hier: https://docs.payone.com/display/public/INT/WooCommerce+Plugin#WooCommercePlugin-CreditNotes - wenn dann noch etwas nicht klappt, kannst du dich auch gerne an unseren Tech Support unter tech.support[ät]bspayone.com wenden.
