### ISSUE TITLE
Credit card form labels are not translatable

### ISSUE THREAD

**Issue by ahegyes** [PAYONE-GmbH/woocommerce-3#4]
Hello!

The text inside the label elements inside the file 'views/gateway/creditcard/payment-form.php' is not translatable. This is less than ideal for German websites.

Thank you!

**Comment by fjbender** [comment]
@hreinberger This seems to be a bug, the `__()` operator was forgotten.

**Comment by hreinberger** [comment]
Hi all,
this should be fixed in v1.3.12. Thanks for the tip!
