### ISSUE TITLE
Wordpress 5.4

### ISSUE THREAD

**Issue by oliverf72** [PAYONE-GmbH/woocommerce-3#45]
Hi, ready for 5.4? Thanks for feedback..

**Comment by hreinberger** [comment]
Hi @oliverf72 
in our recent experience with wordpress 5.4 and woocommerce 4.0.1 we found no breaking changes. Your mileage may vary though - we'll only do a complete test with the current versions of wordpress and woocommerce when we're releasing a new version of our plugin, so I'd advise you to test this yourself if you want to switch to wordpress 5.4 right now - just in case we missed a usecase that's integral to your plugin usage.

**Comment by oliverf72** [comment]
Hallo, mit Woocommerce 4.2 und WP 5.4.2 und Testzugang erhalte ich "Fehler bei Zahlung: „Appointed“ callback wurde nicht empfangen" nach der Zahlung. Kommt noch ein Update oder liegt der Fehler hier woanders? 
Bitte um Feedback. Vielen Dank... 
Oliver Fröhner

**Comment by hreinberger** [comment]
Hi @oliverf72 
wir hatten in der Vergangenheit schon öfter solche Meldungen und haben in #38 einen Fix dafür eingeführt, der im nächsten Release enthalten sein wird. Der Plan sieht ein Release im Juli vor. Wenn du vorher schon ausprobieren möchtest, ob dein Problem damit gelöst wird, kannst du dir jetzt schon den master branch als .zip über github laden und installieren. Beachte aber bitte, dass dieser Stand noch nicht vollständig getestet wurde - probiere das Thema also lieber auf einem Testshop aus. In unseren Tests wurde die Fehlermeldung durch #38 gefixt.
viele Grüße

**Comment by oliverf72** [comment]
Hallo, masterbranch version ist die 1.6.2 oder? Damit habe ich auf Testseite getestet. 
Sofortüberweisung bringt folgende Fehlermeldung " Fehler bei Zahlung: Reference number already exists [911] "

**Comment by hreinberger** [comment]
Den Master lädst du, indem du auf der Hauptseite des Repositorys über "Clone or download" das ZIP herunterlädst. Im Wordpress Backend wird dann zwar Version 1.6.2 angezeigt, der Codestand ist aber neuer.

![grafik](https://user-images.githubusercontent.com/40197225/84862143-eac8a600-b072-11ea-8916-8366d3c64479.png)

**Comment by oliverf72** [comment]
Ok, das habe ich so gemacht. Dennoch bleiben die Fehler bestehen.

**Comment by hreinberger** [comment]
Hm, könntest du dich dazu mal bei unserem Tech Support unter tech.support[at]payone.com melden? Die KollegInnen können sich deine Konfiguration genauer anschauen und betroffene Transaktionen analysieren. Das hilft uns beim Fix weiter. Du kannst gerne einen Link auf diese Unterhaltung dazuschreiben. Ich mache dieses Issue hier so lange zu, denn die Eingangsfrage ist ja beantwortet.
