### ISSUE TITLE
Testcycles for Wordpress v5.4.x

### ISSUE THREAD

**Issue by jangerritha** [PAYONE-GmbH/woocommerce-3#52]
I don't know if an issue is correct for this concern. I was wondering if it is planned to test the plug-in with wordpress v5.4? I currently  integrated the plug-in based on the content of this repo with WP v5.4.1. Everything seems to work, except that I am not sure about the correctnes of the API logs.

**Comment by fjbender** [comment]
We have a test instance up and running with Wordpress 5.4.1, and I don't see any issues with the API log. 

What behavior are you seeing exactly?

**Comment by jangerritha** [comment]
@fjbender We observed a high number of errors for a short time period, but it turned out that a customer repeatedly escaped the payment process. Plugin seems to work as desired.

Thank you for the information on your test setup. I was just confused because the information page at the wordpress site says "not tested with your version."
