### ISSUE TITLE
Payment Gateway Descriptions not correctly translated with WPML String translations.

### ISSUE THREAD

**Issue by jangerritha** [PAYONE-GmbH/woocommerce-3#55]
We use WPML for the translation of our page. So far everything works, also the payment process on the new english page. However, when the User is asked to choose the payment method the payment method titles are translated to english correctly (Vorkasse <--> Payment in advance etc.), but the payment descriptions are not (See attachement). We translated titles and descriptions with WPML's String-Translation Module. Did anyone already experience this problem?
![bspayone_wpml_fehler_GUI](https://user-images.githubusercontent.com/58729749/92379016-02aa4600-f107-11ea-81ef-546214c5af72.png)
![bspayone_wpml_fehler](https://user-images.githubusercontent.com/58729749/92379021-04740980-f107-11ea-9795-92b310a61ef5.png)

**Comment by janschnitzler** [comment]
We have the same problem in our store, is there any update on this?

**Comment by fjbender** [comment]
Sorry, this ticket went by unnoticed.

I'll see what we can do about this.

**Comment by janschnitzler** [comment]
Any updates on this issue?

**Comment by fjbender** [comment]
Unfortunately, this ticket is still in the backlog.
