### ISSUE TITLE
Error with Germanized

### ISSUE THREAD

**Issue by pkrick** [PAYONE-GmbH/woocommerce-3#56]
If I activated the plugin I get these errors in germanized pro (latest release) -> Rechnungen und Lieferscheine

Notice: Trying to get property 'total' of non-object in /html/wordpress-kandel/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 268

Notice: Undefined variable: country in /html/wordpress-kandel/wp-content/plugins/bs-payone-woocommerce/src/Payone/Gateway/GatewayBase.php on line 193

Notice: Trying to get property 'total' of non-object in /html/wordpress-kandel/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 268

Notice: Undefined variable: country in /html/wordpress-kandel/wp-content/plugins/bs-payone-woocommerce/src/Payone/Gateway/GatewayBase.php on line 193

**Comment by hreinberger** [comment]
Hi @pkrick 
we don't have a germanized pro license, so we're unable to reproduce this at the moment, but we'll take a look at the errors and will get in touch with vendidero to clarify things.
Does this occur only with our latest update or have you tried older versions of our plugin?

**Comment by pkrick** [comment]
Hallo Herr Reinberger,

ist deutsch auch OK? Wir haben eine Testumgebung, gerne kann ich Ihnen Zugangsdaten zukommen lassen und Sie können es hier nachvollziehen. Wir hatten es mit keiner vorherigen Version getestet.

**Comment by hreinberger** [comment]
Hi @pkrick 
wir haben einfach mal auf gut Glück versucht, den Code etwas robuster zu machen. Kannst du den PR mal im Testsystem auschecken und testen, ob sich Germanized Pro jetzt wieder nutzen lässt?

**Comment by hreinberger** [comment]
Hi @pkrick kamst du schon zum Testen?

**Comment by pkrick** [comment]
Ja, tatsächlich funktioniert der Code bis jetzt ohne weitere Probleme.

**Comment by hreinberger** [comment]
#57 ist jetzt (endlich) gemerged.
