### ISSUE TITLE
Germanized Fehler - Notice: Trying to get property 'total'

### ISSUE THREAD

**Issue by pkrick** [PAYONE-GmbH/woocommerce-3#61]
Hallo,

nach dem Update von Germanized erhalte ich auf der Einstellungsseite für Rechnungen folgende Meldung:

Notice: Trying to get property 'total' of non-object in /html/wordpress-staging/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 268

Der entsprechende Code in der Datei ist folgender:

	/**
	 * Get the order total in checkout and pay_for_order.
	 *
	 * @return float
	 */
	protected function get_order_total() {

		$total    = 0;
		$order_id = absint( get_query_var( 'order-pay' ) );

		// Gets order total from "pay for order" page.
		if ( 0 < $order_id ) {
			$order = wc_get_order( $order_id );
			$total = (float) $order->get_total();

			// Gets order total from cart/checkout.
		} elseif ( 0 < WC()->cart->total ) {
			$total = (float) WC()->cart->total;
		}

		return $total;
	}

Ich kann hier keine Zahlungsmittel (welche aktiviert sind) von Payone auswählen (siehe [Screenshot](https://staging.kandel.funforest.de/wp-content/uploads/screenshot.png))

**Comment by hreinberger** [comment]
Hi @pkrick wir schauen uns das mal an.

**Comment by pkrick** [comment]
Hallo @hreinberger, 

hatten Sie bereits Zeit einen Blick darauf zu werfen?

**Comment by hreinberger** [comment]
Hi @pkrick die Fehlersuche bei #58 hat leider etwas gedauert, daher kamen wir noch nicht dazu. Ist aber diese Woche dran.

**Comment by pkrick** [comment]
Von Vendidero ( Germanized) habe ich folgende Antwort erhalten, vielleicht hilft es, das Problem etwas einzugrenzen:

Germanized ruft über die Woo-Funktionen einfach nur die verfügbaren Zahlungsarten im Admin-Bereich ab, um die als Optionen bereitstellen zu können. Ich denke, dass sich irgendein anderes Plugin per Filter einklinkt und nicht prüft, ob es sich um einen Request im Frontend handelt oder nicht und dann Probleme bei der Abfrage hat.

**Comment by pkrick** [comment]
Hallo @hreinberger,

konnten Sie den Bug schon identifizieren?

**Comment by hreinberger** [comment]
Leider noch nicht, aber wir sind weiter dran.
