### ISSUE TITLE
Woo 5.3

### ISSUE THREAD

**Issue by oliverf72** [PAYONE-GmbH/woocommerce-3#68]
Hallo, wie ist die Kompatibilität mit Woo 5.3?
Bitte um Feedback. Vielen Dank... 
mit freundlichen Grüßen
Oliver Fröhner

**Comment by hreinberger** [comment]
Moin @oliverf72 
wir haben hier intern mal einen Shop mit dem aktuellen Plugin und Woocommerce 5.3 aufgesetzt und quergetestet. Dabei sind uns keine Auffälligkeiten über den Weg gelaufen. Einen kompletten Test machen wir allerdings nur zu jedem Release des Plugins. Wir haben noch ein größeres Feature in der Pipeline bis zum nächsten Release, daher kann ich hier noch kein komplett grünes Licht geben, bin aber optimistisch, dass sich keine breaking changes eingeschlichen haben. Am besten setzt ihr euch ein Testsystem mit Woocommerce 5.3 und unserem aktuellen Plugin auf und testet eure use cases einmal durch.
viele Grüße!
