### ISSUE TITLE
PayPal - Parameter faulty or missing [1000]

### ISSUE THREAD

**Issue by ahegyes** [PAYONE-GmbH/woocommerce-3#7]
Hello!

When using this plugin, all payment methods work as expectedly, but for the PayPal gateway, the following error comes up every time:
Parameter faulty or missing [1000]

The developer manual from the merchant interface is not helpful either in identifying why the issue occurs. 

Thank you!

**Comment by hreinberger** [comment]
Hi @ahegyes 
yes, the error code 1000 is a pretty generic one, but it points more to an issue on the API side than in our extension. I would advise that you get in touch with our tech support at tech.support@bspayone.com - our colleagues there have access to your API logs and can identify the error quickly.

**Comment by bullviech** [comment]
Ich hänge mich hier an - die Zahlungsart Paypal funktioniert bei unserem Shop seit gestern ebenso nicht mehr. Ticket an BS Payone ist raus. Trotzdem - sowas darf nicht vorkommen!

**Comment by hreinberger** [comment]
Hallo @bullviech 
wie oben schon beschrieben hängt dieser Fehler weniger mit dem Woocommerce Plugin zusammen, sondern wahrscheinlich eher mit PayPal. Hier gibt es leider keine allgemeingültige Lösung, sondern unser Tech Support muss jeden Fall individuell begutachten.

viele Grüße
