### ISSUE TITLE
Fehler wenn Zahlart “Payone SEPA Abbuchung” aktiviert

### ISSUE THREAD

**Issue by cbayer81** [PAYONE-GmbH/woocommerce-3#72]
Hallo,
seit zwei Wochen haben wir in unserem WooCommerce Shop Probleme mit der Zahlart “Payone SEPA Abbuchung”.
Wenn diese Zahlart aktiviert ist, dann kann im checkout keine Zahlart mehr ausgewählt werden. Tatsächlich geschieht nichts, wenn nach Eingabe der Kundendaten die Schaltfläche „Weiter zu Schritt 2“ geklickt wird.
Nachdem die Zahlart “Payone SEPA Abbuchung” wird, funktioniert die Auswahl der anderen Zahlarten wieder.

WordPress 5.8.1
WooCommerce 5.6.0
Germanized für WooCommerce 3.6.0
BS PAYONE WooCommerce 1.7.1

Gruß Christian

**Comment by cbayer81** [comment]
Das Problem ist weiterhin akut.
Es wundert mich, dass weder von PAYONE bzw. @hreinberger noch der Agentur, die dieses Plugin erstellt hat, irgendeine Reaktion kommt.

**Comment by janteuber** [comment]
Hallo @cbayer81 ,
vielen Dank für die Nachricht.
Ich würde Sie bitten, eine Mail an tech.support@payone.com zu schreiben, das Problem nochmals kurz zu schildern und vor allem Ihre PAYONE Daten mit reinzuschreiben. Die Kollegen können dann schauen, ob die Zahlart richtig in unserem System konfiguriert ist.
