### ISSUE TITLE
Article list faulty or incomplete [1610]

### ISSUE THREAD

**Issue by jnz31** [PAYONE-GmbH/woocommerce-3#74]
during the past days 4 orders came in and they all threw the same error: Article list faulty or incomplete [1610]
with no payment nor info inside bs payone.
i guess it is the same issue as [this](https://wordpress.org/support/topic/article-list-faulty-or-incomplete-1610/) one, since all these orders have discounts applied, too. i found some older orders (feb 10, 22) with no coupon/discount and these had no issues.

Wordpress 5.9.0
Woocommerce 6.2.0
BS PAYONE WooCommerce 1.7.1

**Comment by janteuber** [comment]
Hello @jnz31 ,
please send a mail to tech.support@payone.com.

My colleagues need to check the logs to figure out why this error occurred. Please also write what has been changed recently. E.g. installation of new plugins that affect the calculation in the shopping cart.

As this case is very individual, I am closing this Issue.
