### ISSUE TITLE
WooCommerce version: 6.2.1

### ISSUE THREAD

**Issue by ming2014** [PAYONE-GmbH/woocommerce-3#78]
Hi,
I upgraded to WordPress version: 5.9.1 ,WooCommerce version: 6.2.1 showed the error:
<img width="677" alt="20220302205403" src="https://user-images.githubusercontent.com/6830913/157644555-1b472a31-f67d-48b9-bc92-7c4f61acfed6.png">
<img width="581" alt="payone" src="https://user-images.githubusercontent.com/6830913/157644604-e209209c-0bd2-4ac1-aa6d-e715f796372f.png">
,

**Comment by janteuber** [comment]
Hello @ming2014 ,
I use the same setup and do not get this error message. But the path of our plugin on the screenshot looks very strange. It doesn't seem to be our plugin from the normal repository.
We will release a new plugin next week. Please install it and see if the error still occurs.

**Comment by janteuber** [comment]
Hello @ming2014 ,
Do you have any feedback for us?

**Comment by ming2014** [comment]
> 

Hi,
I'm still waiting for a new version to test if this problem persists? Have you released a new version?

**Comment by janteuber** [comment]
Yes, we did: https://github.com/PAYONE-GmbH/woocommerce-3/releases/tag/v2.0.0

**Comment by ming2014** [comment]
> Yes, we did: https://github.com/PAYONE-GmbH/woocommerce-3/releases/tag/v2.0.0

Thank you for your reply.
After using the new version, the problem has been solved, thank you very much!
