### ISSUE TITLE
Die eigene iframe-Höhe bei den Kreditkarteneinstellungen wird nicht übernommen

### ISSUE THREAD

**Issue by davood89** [PAYONE-GmbH/woocommerce-3#93]
In der Datei "payment-form.php" sind im config-Array die falschen PHP-Optionen für die Höhe hinterlegt. Hier wird auch die Breite als Variable eingefügt.

Line 79: cc_field_cardnumber_width
Line 93: cc_field_cvc2_width
Line 106: cc_field_month_width
Line 119: cc_field_year_width

**Comment by janteuber** [comment]
Hello @davood89 ,

Thank you very much for your advice.

A developer will take a look at the case in a timely manner and then provide feedback.

**Comment by janteuber** [comment]
Hello @davood89 ,

We have provided the following pull request for this issue: https://github.com/PAYONE-GmbH/woocommerce-3/pull/94

It is planned to release this PR at the beginning of August.
