### ISSUE TITLE
"No appointed flag set for order" – wirklich ein Fehler?

### ISSUE THREAD

**Issue by twwn** [PAYONE-GmbH/woocommerce-3#99]
Hallo,

seit wir vor 1+ Jahren auf Payone umgestiegen sind, landet in der `debug.log` bei *jeder* erfolgreichen Bestellung (egal welche Zahlweise) [die "Fehlermeldung"](https://github.com/PAYONE-GmbH/woocommerce-3/blob/master/src/Payone/Gateway/RedirectGatewayBase.php#L29):

>No appointed flag set for order ####### before the customer received the checkout success page.

Das hat (soweit wir wissen) noch nie zu irgendwelchen Problemen geführt.

Was sagt die Meldung eigentlich überhaupt aus? Ist da doch irgendwas im Argen mit der Konfiguration? Oder ist es am Ende vielleicht doch gar kein Fehler, wie ursprünglich angenommen?

*edit:* Die Bedingung ist [dann ja auch](https://github.com/PAYONE-GmbH/woocommerce-3/blob/master/src/Payone/Gateway/RedirectGatewayBase.php#L28):

`$order->get_meta( '_appointed' ) > 0`

Dabei wird `_appointed` aber nur einmal im Plugin mit irgendwas beschrieben, [nämlich hier](https://github.com/PAYONE-GmbH/woocommerce-3/blob/master/src/Payone/Gateway/GatewayBase.php#L134) bei `$transaction_status->is_appointed()` (das ist doch eigtl. Erfolg?):

`$order->update_meta_data( '_appointed', time() );`

Kann es damit überhaupt je `<= 0` sein, damit die Meldung nicht ausgegeben wird? Sollte da evtl. nicht die Bedingung so umgekehrt oder ein `!isset()` stehen?

**Comment by hreinberger** [comment]
Moin, das "appointed" bezieht sich auf einen Webhook, den unsere Plattform bei erfolgreich angelegten Zahlungen an den Shop schickt. Wie die zu konfigurieren sind, haben wir hier dokumentiert: https://docs.payone.com/display/public/INT/Integrationsanleitung+WooCommerce#IntegrationsanleitungWooCommerce-KonfigurationimPAYONE-Portal 

Die meisten Transaktionen funktionieren auch ohne Webhooks, aber ihr solltet trotzdem einmal prüfen, ob der Endpunkt richtig gesetzt ist. Sonst kann es z.B. dazu kommen, dass Transaktionen auf der PAYONE Plattform gar nicht angelegt werden, ihr aber trotzdem eine korrekte Bestellung im Backend seht (z.B. bei Weiterleitungszahlarten). Außerdem schicken wir Webhooks, wenn es Chargebacks oder Disputes für einzelne Zahlungen gibt.

Wenn die Einstellung bei euch richtig ist, wende dich bitte einmal an unseren tech support unter tech(punkt)support(ät)payone(punkt)com - die KollegInnen prüfen dann einmal die Konfig im Backend und geben das Thema bei Bedarf an uns zur Prüfung zurück.

viele Grüße!

**Comment by twwn** [comment]
Hallo, die TS-URL war tatsächlich noch auf die alte gesetzt, das habe ich im Changelog wohl übersehen.

Allerdings kommt auch mit der neuen immer noch dieselbe "Fehlermeldung" im `debug.log`.

Wie in meinem Edit oben geschrieben, kann der Code des Plugins überhaupt etwas anderes ausgeben? Es kann doch niemals ein Wert `<= 0` von ihm geschrieben werden, damit die Fehler-Bedingung nicht getroffen würde.
